# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
   apt:
     packages:
       - libgsl0-dev # for topicmodels
       - libxml2-dev # for XML, a dependency of quanteda
       - libnetcdf-dev # for ncdf4
       - netcdf-bin #for ncdf4
       
before_install:
 - wget http://cirrus.ucsd.edu/~pierce/ncdf/ncdf4_1.13.tar.gz
 - R CMD INSTALL ncdf4_1.13.tar.gz
